config:
  ape:
    ape_class: LearnableAbsolutePosition
  dataset:
    columns:
    - Label
    - Timestamp
    - Date
    - Node
    - Time
    - NodeRepeat
    - Type
    - Component
    - Level
    - Content
    name: BGL
    path: data\BGL\BGL.log
  decoder:
    decoder_class: CollaborativeAttention
  device: cpu
  model:
    context_length: 100
    dropout: 0.1
    embed_dim: 512
    ffn_dim: 2048
    max_len: 512
    num_groups: 8
    num_heads: 8
    num_layers: 6
    num_windows: 30
    prediction_steps: 20
    vocab_size: 1824
  rpe:
    rpe_class: LearnableRelativePosition
  training:
    batch_size: 10
    num_epochs: 2
config_name: base_config
